### ISSUE TITLE
jco cli No such file or directory (os error 44) on Windows for --wit

### ISSUE THREAD

**Issue by rajsite** [bytecodealliance/jco#170]
Tried to run the example shown here: https://component-model.bytecodealliance.org/language-support/javascript.html

Reproduced as follows:
```
Now, use jco to create a component from the JS module:
$ jco componentize add.js --wit add.wit -n example -o add.wasm
OK Successfully written add.wasm with imports ().
```

But run into the error:
```
> jco componentize add.js --wit add.wit -n example -o add.wasm

(jco componentize) ComponentError: failed to read file "C:\\Users\\mraj\\Desktop\\path-issue\\add.wit"

Caused by:
    No such file or directory (os error 44)
    at spliceBindings (file:///C:/Users/mraj/Desktop/path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:3133:11)
    at componentize (file:///C:/Users/mraj/Desktop/path-issue/node_modules/@bytecodealliance/componentize-js/src/componentize.js:32:64)
    at async componentize (file:///C:/Users/mraj/Desktop/path-issue/node_modules/@bytecodealliance/jco/src/cmd/componentize.js:15:34)
    at async file:///C:/Users/mraj/Desktop/path-issue/node_modules/@bytecodealliance/jco/src/jco.js:128:9
```

Reproduction:
Extract [path-issue.zip](https://github.com/bytecodealliance/jco/files/12807340/path-issue.zip), run `npm ci`, and `npm run build:cli`

Workaround:
Use the componentize node api like shown here: https://github.com/bytecodealliance/componentize-js/blob/main/EXAMPLE.md
Can be seen in the reproduction via `npm run build:script`

Environment:
Windows 10
Node v18.16.1

**Comment by guybedford** [comment]
@rajsite did you have an `add.wit` file present in the local directory? You may need to update the path to the right location for it I think there?

**Comment by rajsite** [comment]
> @rajsite did you have an `add.wit` file present in the local directory? You may need to update the path to the right location for it I think there?

Yep, see the attached zip reproduction

**Comment by rajsite** [comment]
Having similar issues trying to create a wit dir and using witPath like done here: https://github.com/bytecodealliance/componentize-js/blob/668cb80f8b0bc283abc68e695c915598ea021162/test/test.js#L146

```
> node hello.build.js

file:///C:/dev/azdo/mraj-wasm-components/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:3133
    throw new ComponentError(variant26.val);
          ^

ComponentError: failed to read file "C:\\dev\\azdo\\mraj-wasm-components\\packages\\component-exercises\\wit"

Caused by:
    No such file or directory (os error 44)
    at spliceBindings (file:///C:/dev/azdo/mraj-wasm-components/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:3133:11)
    at componentize (file:///C:/dev/azdo/mraj-wasm-components/node_modules/@bytecodealliance/componentize-js/src/componentize.js:32:64)
    at async file:///C:/dev/azdo/mraj-wasm-components/packages/component-exercises/hello.build.js:7:23
```

**Comment by guybedford** [comment]
Hmm, maybe this is a Windows issue? So the path that is claimed to not exist definitely does? I will try this on a Windows machine then.

**Comment by rajsite** [comment]
> Hmm, maybe this is a Windows issue? So the path that is claimed to not exist definitely does? I will try this on a Windows machine then.

Yea in both cases the paths definitely exist.
Context is I'm trying to run through these examples with jco / componentize-js on windows: https://github.com/alexcrichton/bacon-exercises
https://alexcrichton.github.io/bacon-exercises/#hello

**Comment by rajsite** [comment]
> > Hmm, maybe this is a Windows issue? So the path that is claimed to not exist definitely does? I will try this on a Windows machine then.
> 
> Yea in both cases the paths definitely exist. Context is I'm trying to run through these examples with jco / componentize-js on windows: https://github.com/alexcrichton/bacon-exercises https://alexcrichton.github.io/bacon-exercises/#hello

This is a minimal reproduction of a similar issue I ran into with witPath and couldn't think of a workaround in this case:
[wit-path-issue.zip](https://github.com/bytecodealliance/jco/files/12809258/wit-path-issue.zip)

Extract, `npm ci`, and `npm run build` on windows results in error:
```
C:\Users\mraj\Desktop\wit-path-issue>npm run build

> wit-path-issue@1.0.0 build
> node build.js

file:///C:/Users/mraj/Desktop/wit-path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:3133
    throw new ComponentError(variant26.val);
          ^

ComponentError: failed to read file "C:\\Users\\mraj\\Desktop\\wit-path-issue\\wit"

Caused by:
    No such file or directory (os error 44)
    at spliceBindings (file:///C:/Users/mraj/Desktop/wit-path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:3133:11)
    at componentize (file:///C:/Users/mraj/Desktop/wit-path-issue/node_modules/@bytecodealliance/componentize-js/src/componentize.js:32:64)
    at async file:///C:/Users/mraj/Desktop/wit-path-issue/build.js:7:23

Node.js v18.16.1
```

**Comment by rajsite** [comment]
Neither of the above examples (path-issue.zip with `npm run build:cli` or it-path-issue.zip with `npm run build`) seem to work on Ubuntu 22.04.3 LTS with node v20.8.0 either. Get a different set of errors:
```
mraj@mraj-virtual-machine:~/Downloads/wit-path-issue$ npm run build

> wit-path-issue@1.0.0 build
> node build.js

RangeError: Division by zero
    at nsToDateTime (file:///home/mraj/Downloads/wit-path-issue/node_modules/@bytecodealliance/preview2-shim/lib/nodejs/filesystem.js:71:33)
    at stat (file:///home/mraj/Downloads/wit-path-issue/node_modules/@bytecodealliance/preview2-shim/lib/nodejs/filesystem.js:230:28)
    at trampoline16 (file:///home/mraj/Downloads/wit-path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:1174:29)
    at wit-component:shim.indirect-wasi:filesystem/types-stat (wasm://wasm/wit-component:shim-98160e1e:wasm-function[6]:0x1b3)
    at wit-component:adapter:wasi_snapshot_preview1._ZN22wasi_snapshot_preview18bindings4wasi10filesystem5types4stat17h0fec3a4c56bcb401E (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[75]:0x5bc1)
    at wit-component:adapter:wasi_snapshot_preview1.fd_filestat_get (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[45]:0x1ee6)
    at wit-component:shim.adapt-wasi_snapshot_preview1-fd_filestat_get (wasm://wasm/wit-component:shim-98160e1e:wasm-function[23]:0x29b)
    at _ZN4wasi13lib_generated15fd_filestat_get17h9cac52ab496f62a2E (wasm://wasm/015bfc9a:wasm-function[4811]:0x291d7c)
    at _ZN3std2fs14read_to_string5inner17h81529b91530e20f4E (wasm://wasm/015bfc9a:wasm-function[4712]:0x28b574)
    at _ZN10wit_parser3ast9SourceMap9push_file17h78d4bda0a03ef871E (wasm://wasm/015bfc9a:wasm-function[3824]:0x2214f7)
file:///home/mraj/Downloads/wit-path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:1400
          throw new TypeError(`"${val5}" is not one of the cases of error-code`);
                ^

TypeError: "RangeError: Division by zero" is not one of the cases of error-code
    at trampoline16 (file:///home/mraj/Downloads/wit-path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:1400:17)
    at wit-component:shim.indirect-wasi:filesystem/types-stat (wasm://wasm/wit-component:shim-98160e1e:wasm-function[6]:0x1b3)
    at wit-component:adapter:wasi_snapshot_preview1._ZN22wasi_snapshot_preview18bindings4wasi10filesystem5types4stat17h0fec3a4c56bcb401E (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[75]:0x5bc1)
    at wit-component:adapter:wasi_snapshot_preview1.fd_filestat_get (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[45]:0x1ee6)
    at wit-component:shim.adapt-wasi_snapshot_preview1-fd_filestat_get (wasm://wasm/wit-component:shim-98160e1e:wasm-function[23]:0x29b)
    at _ZN4wasi13lib_generated15fd_filestat_get17h9cac52ab496f62a2E (wasm://wasm/015bfc9a:wasm-function[4811]:0x291d7c)
    at _ZN3std2fs14read_to_string5inner17h81529b91530e20f4E (wasm://wasm/015bfc9a:wasm-function[4712]:0x28b574)
    at _ZN10wit_parser3ast9SourceMap9push_file17h78d4bda0a03ef871E (wasm://wasm/015bfc9a:wasm-function[3824]:0x2214f7)
    at _ZN10wit_parser17UnresolvedPackage9parse_dir17he83ab980bba1c98fE (wasm://wasm/015bfc9a:wasm-function[4094]:0x2521e7)
    at _ZN10wit_parser7resolve7Resolve8push_dir17h2f9303f068df4162E (wasm://wasm/015bfc9a:wasm-function[3767]:0x2089a8)

Node.js v20.8.0

```

**Comment by guybedford** [comment]
Thanks for posting, I'm working on getting up a Windows fix today. Should have something up soon.

**Comment by rajsite** [comment]
@guybedford I saw this was merged which is great! Is there a release / prerelease package to play with? Wasn't sure how often releases are made.

**Comment by guybedford** [comment]
@rajsite the next release will likely only be in a week or so yet, there are a number of changes in play, and the new toolchain upgrade will be going through next week. I'd suggest cloning the repo if you're interested in testing in the meantime. I will still check your other case you posted as well.

**Comment by rajsite** [comment]
@guybedford sounds great! Appreciate the response :)
