### ISSUE TITLE
jco tooling can't handle unusual file timestamps

### ISSUE THREAD

**Issue by rajsite** [bytecodealliance/jco#171]
On Ubuntu 22.04.3 LTS with node v20.8.0 download the following zip file and extract the contents interactively in ubuntu (right click and "extract here").

[path-issue.zip](https://github.com/bytecodealliance/jco/files/12809990/path-issue.zip)

Run `npm ci` and `npm run build:cli` and note the following error:
```
mraj@mraj-virtual-machine:~/Downloads/path-issue$ npm run build:cli

> path-issue@1.0.0 build:cli
> jco componentize add.js --wit add.wit -n example -o add.wasm

RangeError: Division by zero
    at nsToDateTime (file:///home/mraj/Downloads/path-issue/node_modules/@bytecodealliance/preview2-shim/lib/nodejs/filesystem.js:71:33)
    at statAt (file:///home/mraj/Downloads/path-issue/node_modules/@bytecodealliance/preview2-shim/lib/nodejs/filesystem.js:253:28)
    at trampoline17 (file:///home/mraj/Downloads/path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:1424:29)
    at wit-component:shim.indirect-wasi:filesystem/types-stat-at (wasm://wasm/wit-component:shim-98160e1e:wasm-function[7]:0x1c5)
    at wit-component:adapter:wasi_snapshot_preview1._ZN22wasi_snapshot_preview18bindings4wasi10filesystem5types7stat_at17h38f02de6d266ab51E (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[76]:0x5c7e)
    at wit-component:adapter:wasi_snapshot_preview1.path_filestat_get (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[52]:0x3eac)
    at wit-component:shim.adapt-wasi_snapshot_preview1-path_filestat_get (wasm://wasm/wit-component:shim-98160e1e:wasm-function[27]:0x2df)
    at _ZN4wasi13lib_generated17path_filestat_get17h562e977a5cbab73bE (wasm://wasm/015bfc9a:wasm-function[4815]:0x291f69)
    at _ZN3std3sys4wasi2fs4stat17haeb27919410a63e5E (wasm://wasm/015bfc9a:wasm-function[4727]:0x28ce7c)
    at _ZN3std4path4Path6is_dir17h061ef12d0d2029f3E (wasm://wasm/015bfc9a:wasm-function[4728]:0x28d026)
(jco componentize) TypeError: "RangeError: Division by zero" is not one of the cases of error-code
    at trampoline17 (file:///home/mraj/Downloads/path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:1650:17)
    at wit-component:shim.indirect-wasi:filesystem/types-stat-at (wasm://wasm/wit-component:shim-98160e1e:wasm-function[7]:0x1c5)
    at wit-component:adapter:wasi_snapshot_preview1._ZN22wasi_snapshot_preview18bindings4wasi10filesystem5types7stat_at17h38f02de6d266ab51E (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[76]:0x5c7e)
    at wit-component:adapter:wasi_snapshot_preview1.path_filestat_get (wasm://wasm/wit-component:adapter:wasi_snapshot_preview1-000203b6:wasm-function[52]:0x3eac)
    at wit-component:shim.adapt-wasi_snapshot_preview1-path_filestat_get (wasm://wasm/wit-component:shim-98160e1e:wasm-function[27]:0x2df)
    at _ZN4wasi13lib_generated17path_filestat_get17h562e977a5cbab73bE (wasm://wasm/015bfc9a:wasm-function[4815]:0x291f69)
    at _ZN3std3sys4wasi2fs4stat17haeb27919410a63e5E (wasm://wasm/015bfc9a:wasm-function[4727]:0x28ce7c)
    at _ZN3std4path4Path6is_dir17h061ef12d0d2029f3E (wasm://wasm/015bfc9a:wasm-function[4728]:0x28d026)
    at splice-bindings (wasm://wasm/015bfc9a:wasm-function[99]:0x1dd43)
    at spliceBindings (file:///home/mraj/Downloads/path-issue/node_modules/@bytecodealliance/componentize-js/lib/spidermonkey-embedding-splicer.js:2986:42)

```

Workaround:

Run `touch *` and then attempt to run the above command again and notice that it succeeds.

**Comment by guybedford** [comment]
I believe this should be resolved in the latest Preview2 implementation, but please post back / share a replication if that it comes up again.
