### ISSUE TITLE
Version 0.11.1 onwards doesn't work in StackBlitz

### ISSUE THREAD

**Issue by BrianJDrake** [bytecodealliance/jco#222]
Steps to reproduce:

1. Using Chromium 117.0.5938.132, open a [new Node.js project](https://stackblitz.com/fork/github/stackblitz/starters/tree/main/node) in StackBlitz.
1. Run `npm install @bytecodealliance/jco@0.11.1 && jco -h`.

Expected results:

`jco` prints a help screen.

Actual results:

```
$ npm install @bytecodealliance/jco@0.11.1 && jco -h

added 51 packages in 12s

20 packages are looking for funding
  run `npm fund` for details
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at ESMLoader.<anonymous> (https://stackblitzstarters7wytti-h5s1.w-credentialless.staticblitz.com/blitz.1f9496ab.js:189:1576)
    at ESMLoader.<anonymous> (https://stackblitzstarters7wytti-h5s1.w-credentialless.staticblitz.com/blitz.1f9496ab.js:248:8318)
```

The error remains present in the latest version, 0.12.2:

```
$ npm install @bytecodealliance/jco@0.12.2 && jco -h

changed 2 packages in 9s

20 packages are looking for funding
  run `npm fund` for details
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at ESMLoader.<anonymous> (https://stackblitzstarters7wytti-h5s1.w-credentialless.staticblitz.com/blitz.1f9496ab.js:189:1576)
    at ESMLoader.<anonymous> (https://stackblitzstarters7wytti-h5s1.w-credentialless.staticblitz.com/blitz.1f9496ab.js:248:8318)
```

But version 0.11.0 works:

```
$ npm install @bytecodealliance/jco@0.11.0 && jco -h

changed 2 packages in 5s

20 packages are looking for funding
  run `npm fund` for details
Usage: jco <command> [options]

jco - WebAssembly JS Component Tools
      JS Component Transpilation Bindgen & Wasm Tools for JS

Options:
  -V, --version                         output the version number
  -h, --help                            display help for command

Commands:
  componentize [options] <js-source>    Create a component from a JavaScript module
  transpile [options] <component-path>  Transpile a WebAssembly Component to JS + core Wasm for JavaScript execution
  opt [options] <component-file>        optimizes a Wasm component, including running wasm-opt Binaryen optimizations
  wit [options] <component-path>        extract the WIT from a WebAssembly Component [wasm-tools component wit]
  print [options] <input>               print the WebAssembly WAT text for a binary file [wasm-tools print]
  metadata-show [options] [module]      extract the producer metadata for a Wasm binary [wasm-tools metadata show]
  metadata-add [options] [module]       add producer metadata for a Wasm binary [wasm-tools metadata add]
  parse [options] <input>               parses the Wasm text format into a binary file [wasm-tools parse]
  new [options] <core-module>           create a WebAssembly component adapted from a component core Wasm [wasm-tools
                                        component new]
  embed [options] [core-module]         embed the component typing section into a core Wasm module [wasm-tools component
                                        embed]
  help [command]                        display help for command
```

**Comment by BrianJDrake** [comment]
The problem is with this line (version 0.12.2, `obj/wasm-tools.js`, line 2673):

```
export { tools, tools as 'local:wasm-tools/tools' }
```

It doesn't like the string identifier.

**Comment by BrianJDrake** [comment]
This doesn't seem to be a `jco` issue.
