### ISSUE TITLE
wasi-http-proxy tests are failing using node < 20

### ISSUE THREAD

**Issue by manekinekko** [bytecodealliance/jco#311]
running `npm test` fails for node **18.15, 18.16, 18.17, 18.18, 18.19** - but works fine for node 20+

```
  1) Preview 2
       wasi-http-proxy:
     Error: node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

AssertionError [ERR_ASSERTION]: '{"status":200,"headers":[["content-type","text/plain"],["x-wasi","mock-server"],["date","null"],["connection","close"],["transfer-encoding","chunked"]],"body":"hello world"}' == '{"status":200,"headers":[["content-type","text/plain"],["x-wasi","mock-server"],["date","null"],["connection","keep-alive"],["keep-alive","timeout=5"],["transfer-encoding","chunked"]],"body":"hello world"}'
    at file:///home/wassimchegham/oss/@bytecodealliance/jco/test/output/wasi-http-proxy.js:12:8 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: '{"status":200,"headers":[["content-type","text/plain"],["x-wasi","mock-server"],["date","null"],["connection","close"],["transfer-encoding","chunked"]],"body":"hello world"}',
  expected: '{"status":200,"headers":[["content-type","text/plain"],["x-wasi","mock-server"],["date","null"],["connection","keep-alive"],["keep-alive","timeout=5"],["transfer-encoding","chunked"]],"body":"hello world"}',
  operator: '=='
}

Node.js v18.15

      at ChildProcess.<anonymous> (file:///home/wassimchegham/oss/@bytecodealliance/jco/test/helpers.js:17:59)
      at ChildProcess.emit (node:events:514:28)
      at ChildProcess._handle.onexit (node:internal/child_process:291:12)

```

![image](https://github.com/bytecodealliance/jco/assets/1699357/ec8c6d5e-e20e-4084-8e28-6f83f33c0899)

**Comment by manekinekko** [comment]
@guybedford what is the minimum node version jco supports? should we enforce that? jco cli can print a warning / or exit if the supported node version is not met. wdyt?

**Comment by guybedford** [comment]
Thanks for finding these failures, yes this is a regression from the HTTP work, I'll look into it. We should support Node.js LTS which means 18+.
