### ISSUE TITLE
Better errors when failing to parse a wit directory

### ISSUE THREAD

**Issue by bakkot** [bytecodealliance/jco#442]
I wanted to try the [fancy new feature to generate types from a directory](https://github.com/bytecodealliance/jco/pull/426), so I made a directory with two `.wit` files and ran `node src/jco.js types ./wit-dir -o ./types`, which produced

```
(jco types) ComponentError: failed to parse package: /code/jco/wit-dir
    at generateTypes (file:///code/jco/obj/js-component-bindgen-component.js:3976:11)
    at typesComponent (file:///code/jco/src/cmd/transpile.js:45:29)
    at async types (file:///code/jco/src/cmd/transpile.js:18:17)
    at async file:///code/jco/src/jco.js:186:9
```

Which is really not a helpful error.

Eventually by looking at the tests folder I was able to figure out that I'm supposed to have a single `.wit` file at the top level of `wit-dir` and put other files under the `deps` folder, but I don't know how I was supposed to figure that out without looking at the tests.

---

Also, on a related note, when there's a syntax error in the top-level `.wit` file it says `failed to parse package:/code/jco/wit-dir` rather than naming the file, or giving any information about what the error is.

**Comment by itowlson** [comment]
This error also occurs if you make a mistake in your WIT (e.g. writing `static foo: func()` instead of `foo: static func()`).  It would be nice if `jco types` pointed you to what the error was and where; at the moment I have to run the WIT through wit-bindgen to find out where I messed up.

**Comment by vados-cosmonic** [comment]
@itowlson is totally right here, but `jco` definitely aims to do a better job exposing the error and what exactly went wrong. @bakkot I'll take a look at this and see if we can't improve the message that gets written out (assuming we haven't already!).

> Also, on a related note, when there's a syntax error in the top-level .wit file it says failed to parse package:/code/jco/wit-dir rather than naming the file, or giving any information about what the error is.

With regards to this, I believe this is because we give the WIT directory usually rather than a single file. Of course, it is nice to know *which* file failed :)
