### ISSUE TITLE
Still having issues with the env vars memory leak

### ISSUE THREAD

**Issue by pimeys** [bytecodealliance/jco#453]
Hi, I read this issue which was supposedly closed by implementing a new allocator in the reactor component. Currently still even the most basic example with `jco` crashes:

```
❯ npx jco types world.wit -n gateway -o types
unreachable executed at adapter line 214: out of memory

(jco types) RuntimeError: unreachable
    at wasm://wasm/0001823a:wasm-function[39]:0xffb
    at wasm://wasm/0001823a:wasm-function[38]:0xb55
    at utf8Encode (file:///home/pimeys/code/grafbase/demo-component/ts-demo/node_modules/@bytecodealliance/jco/obj/js-component-bindgen-component.js:120:11)
    at trampoline31 (file:///home/pimeys/code/grafbase/demo-component/ts-demo/node_modules/@bytecodealliance/jco/obj/js-component-bindgen-component.js:3393:16)
    at wasm://wasm/df4ce642:wasm-function[20]:0x27c
    at wasm://wasm/0001823a:wasm-function[43]:0x1648
    at wasm://wasm/0001823a:wasm-function[44]:0x184c
    at wasm://wasm/df4ce642:wasm-function[32]:0x328
    at wasm://wasm/00826e82:wasm-function[4992]:0x1bfce0
    at wasm://wasm/00826e82:wasm-function[5005]:0x1c00f1
```

Now, I solved this with Rust and cargo-component by defining a custom reactor:

```toml
[package.metadata.component]
adapter = "./wasi_snapshot_preview1.reactor.wasm"
```

Where the reactor is downloaded from here:

https://github.com/bytecodealliance/wasmtime/releases

I'm asking is there a way to define custom adapters for jco? I can see the adapters in node_modules, but manually replacing them there feels wrong.

**Comment by guybedford** [comment]
This should be working in the latest Jco now, please let me know if you're still having any issues at all.
