### ISSUE TITLE
"module is invalid", "failed to find export of interface" of the imported interface

### ISSUE THREAD

**Issue by cataggar** [bytecodealliance/jco#534]
When I add `import ts:typescript-system/types@0.1.0;`, I get an error that the "module is invalid" and it "failed to find export of interface":

```
$ bunx jco componentize world.js --wit wit -o ts-typescript.wasm -d all
ComponentError: failed to encode a component from module
$failed to decode world from module

Caused by:
    0: module was not valid
    1: failed to find export of interface `ts:typescript-system/types@0.1.0` function `[constructor]system`
    at componentNew (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/obj/wasm-tools.js:3618:11)
    at componentNew (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/api.js:37:10)
    at async componentize (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/componentize-js/src/componentize.js:381:5)
    at async componentize (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/cmd/componentize.js:11:25)
    at async file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/jco.js:200:9
error: script "componentize" exited with code 1
(jco componentize) 
In 'typescript' script 'componentize' failed with exit code 1
```

I'll followup with full steps to reproduce.

**Comment by cataggar** [comment]
Full steps to reproduce are in https://github.com/cataggar/StarlingMonkey15/blob/jco534/README.md .

```
git clone git@github.com:cataggar/StarlingMonkey15.git --no-checkout
cd StarlingMonkey15
git checkout jco534

bun install
bun run build.ts
```

Sample output:
```
~/ms/StarlingMonkey15> bun run build.ts
$ wkg wit fetch

$ cargo component build
  Generating bindings for typescript-system (src/bindings.rs)
   Compiling typescript-system v0.1.0 (/Users/cataggar/ms/StarlingMonkey15/typescript-system)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.61s
    Creating component target/wasm32-wasip1/debug/typescript_system.wasm

$ wkg wit fetch

$ bunx jco types wit -o .

  Generated Type Files:

 - ./interfaces/ts-typescript-system-types.d.ts  0.14 KiB
 - ./interfaces/ts-typescript-typescript.d.ts    0.17 KiB
 - ./interfaces/wasi-io-poll.d.ts                1.36 KiB
 - ./wit.d.ts                                    0.28 KiB


$ bun run bundle.ts

$ bunx jco componentize world.js --wit wit -o ts-typescript.wasm -d all
ComponentError: failed to encode a component from module
$failed to decode world from module

Caused by:
    0: module was not valid
    1: failed to find export of interface `ts:typescript-system/types@0.1.0` function `[constructor]system`
    at componentNew (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/obj/wasm-tools.js:3618:11)
    at componentNew (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/api.js:37:10)
    at async componentize (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/componentize-js/src/componentize.js:381:5)
    at async componentize (file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/cmd/componentize.js:11:25)
    at async file:///Users/cataggar/ms/StarlingMonkey15/node_modules/@bytecodealliance/jco/src/jco.js:200:9
error: script "componentize" exited with code 1
(jco componentize) 
In 'typescript' script 'componentize' failed with exit code 1
```

**Comment by cataggar** [comment]
I'm trying to accomplish this, but with the 2nd component build with JCO, not Rust. Here is a working Rust component.
https://github.com/cataggar/StarlingMonkey15/blob/rs-rs-rs/README.md

**Comment by guybedford** [comment]
Had a look at this, and if I run `wasm-tools component wit` on the constructed binary that is throwing in `componentNew` there I get the following output:

```
world root {
  import ts:typescript-system/types@0.1.0;
  import wasi:io/poll@0.2.2;
  import wasi:cli/environment@0.2.2;

  export ts:typescript/typescript@0.1.0;
  export ts:typescript-system/types@0.1.0;
}
package ts:typescript-system@0.1.0 {
  interface types {
    resource system {
      constructor();
      get-arguments: func() -> list<string>;
    }
  }
}


package wasi:io@0.2.2 {
  interface poll {
    resource pollable {
      ready: func() -> bool;
      block: func();
    }

    poll: func(in: list<borrow<pollable>>) -> list<u32>;
  }
}


package wasi:cli@0.2.2 {
  interface environment {
    get-environment: func() -> list<tuple<string, string>>;

    get-arguments: func() -> list<string>;

    initial-cwd: func() -> option<string>;
  }
}


package ts:typescript@0.1.0 {
  interface typescript {
    resource program {
      constructor();
      concat-arguments: func() -> string;
    }
  }
  world root {
    import ts:typescript-system/types@0.1.0;
    import wasi:io/poll@0.2.2;
    import wasi:cli/environment@0.2.2;

    export typescript;
    export ts:typescript-system/types@0.1.0;
  }
}
```

Therefore the final world is expected to export the `typescript-system/types` interface in order to support the transitive usage.

This seems like a bug in ComponentizeJS that it doesn't automatically support figuring out these dependencies.

I'm transferring this to the ComponentizeJS project.
